//this variable will hold a random number generated by the random() function
long len;
long t3;
long t4;
float t1;
float t2;
unsigned long m1 = 0;
unsigned long m3 = 0;
const int ledPin =  LED_BUILTIN;
int ledState = LOW; 

//Set up - this is where you get things "set-up". It will only run once
void setup() {
  
  //setup serial communications through the USB
  Serial.begin(9600);
  len = random(5,10); 
  t1 = random(1, 5000); // seconds
  t2 = random(1, 5000); // seconds
  t3 = t1;//*1000;
  t4 = t2;//1000;
  m1 = millis();
  m3 = millis();
  pinMode(ledPin, OUTPUT);
  //Let's make it more random
  randomSeed(42);   
      
}//close setup
 
void loop() {
  
  //generate a random number
  unsigned long m2 = millis();
  unsigned long m4 = millis();
 // Serial.println(m1);
 // Serial.println(m2);
 // Serial.println(t3);
  if (m2-m1 >= t3)
  {
    m1 = m2;
    Serial.print("Turn led on/off \n");
    if (ledState == LOW)
    {
      ledState = HIGH;
    }
    else
    {
      ledState = LOW;
    }

    // set the LED with the ledState of the variable:
    digitalWrite(ledPin, ledState);
  }
  
  if (m4 - m3 >= t4)
  {
    m3 = m4;
    Serial.print("Print random String \n");
  }
}
